default['jenkins-configurer']['user'] = "jenkins"
default['jenkins-configurer']['group'] = "jenkins"
default['jenkins-configurer']['home'] = "/var/lib/jenkins"
default['jenkins-configurer']['email'] = "jenkins@acme.org"
default['jenkins-configurer']['master-host'] = "ci.acme.org"