---
driver:
  name: docker
driver_config:
  use_sudo: false
  require_chef_omnibus: true
  privileged: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: jenkins-base
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[kurento::jenkins-base]
    attributes: 
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team"
          password: "kur3nt0"

  - name: kurento-docker
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[kurento::jenkins-base]
      - recipe[kurento::docker]
    attributes: 
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team"
          password: "kur3nt0"

  - name: kurento-dev-integration
    run_list:
      - recipe[kurento::jenkins-base]
      - recipe[kurento::kurento-dev-integration]
    attributes:
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team"
          password: "kur3nt0"

  - name: kurento-dev-media-server
    run_list:
      - recipe[kurento::jenkins-base]
      - recipe[kurento::kurento-dev-media-server]
    attributes:
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team"
          password: "kur3nt0"

  - name: kurento-dev-debian
    run_list:
      - recipe[kurento::jenkins-base]
      - recipe[kurento::kurento-dev-debian]
    attributes:
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team"
          password: "kur3nt0"

