---
driver:
  name: vagrant
driver_config:
  use_sudo: false
  provision_command: curl -L https://www.chef.io/chef/install.sh | bash -s -- -v 12.0.3

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

suites:
  - name: docker-1.9
    driver:
      customize:
        memory: 1024
    run_list:
      - recipe[apt]
      - recipe[kurento::jenkins-base]
      - recipe[kurento::docker]
    attributes:
      kurento:
        home: '/home/vagrant'
        user: 'vagrant'
        group: 'vagrant'
        npm:
          username: 'vagrantnpmtest'
          password: 'vagrantnpmtest'
          email: 'test@acme.org'
        docker:
          version: '1.9.1-0~trusty'
        docker-compose:
          version: '1.4.0'

  - name: docker-1.11
    driver:
      customize:
        memory: 1024
    run_list:
      - recipe[apt]
      - recipe[kurento::jenkins-base]
      - recipe[kurento::docker]
    attributes:
      kurento:
        home: '/home/vagrant'
        user: 'vagrant'
        group: 'vagrant'
        npm:
          username: 'vagrantnpmtest'
          password: 'vagrantnpmtest'
          email: 'test@acme.org'
        docker:
          version: '1.11.1-0~trusty'
        docker-compose:
          version: '1.7.0'

  - name: kurento-demo
    run_list:
      - recipe[kurento::kurento-demo]
    attributes:
      kurento:
        demo:
          packages: []

  - name: kurento-demo-6
    run_list:
      - recipe[kurento::kurento-demo]
    attributes:
      kurento:
        demo:
          packages: []
        kurento-media-server:
          package-version: '6.0'
        kurento-module-creator:
          package-version: '4.0'

  - name: chef
    driver:
      customize:
        memory: 2048
    run_list:
      - recipe[kurento::chef]

  - name: selenium
    driver:
      customize:
        memory: 2048
    run_list:
      - recipe[apt]
      - recipe[kurento::selenium]

  - name: node
    driver:
      customize:
        memory: 1024
    run_list:
      - recipe[apt]
      - recipe[kurento::npm]
    attributes:
      kurento:
        home: '/home/vagrant'
        user: 'vagrant'
        group: 'vagrant'
        npm:
          username: 'vagrantnpmtest'
          password: 'vagrantnpmtest'
          email: 'test@acme.org'
