---
driver:
  name: docker
driver_config:
  use_sudo: false
  provision_command: 
    - curl -L https://www.getchef.com/chef/install.sh | bash
    - locale-gen en_US.UTF-8
    - echo 'export LANG="en_US.UTF-8"' >> /etc/profile
    - echo 'export LANGUAGE="en_US:en"' >> /etc/profile
    - echo 'export LC_ALL="en_US.UTF-8"' >> /etc/profile
    - export LANG="en_US.UTF-8" && export LANGUAGE="en_US:en" && export LC_ALL="en_US.UTF-8"

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: docker
    run_list:
      - recipe[kurento::docker]
    driver_config:
      privileged: true

  - name: kurento-media-server-dev
    run_list:
      - recipe[kurento::ubuntu-ppa]
      - recipe[kurento::ubuntu-repo]
      - recipe[kurento::kms]
    attributes:
      kurento:
        kurento-media-server:
          package-version: '6.0'

  - name: kurento-media-server-release
    run_list:
      - recipe[kurento::ubuntu-ppa]
      - recipe[kurento::ubuntu-repo]
      - recipe[kurento::kms]
    attributes:
      kurento:
        kurento-media-server:
          package-version: '5.0'

  - name: npm
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[kurento::jenkins-base]
      - recipe[kurento::npm]
    attributes: 
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team-test"
          password: "kur3nt0"

  - name: jenkins-base
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[kurento::jenkins-base]
    attributes: 
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team-test"
          password: "kur3nt0"

  - name: integration
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[kurento::ubuntu-ppa]
      - recipe[kurento::ubuntu-repo]
      - recipe[kurento::jenkins-base]
      - recipe[kurento::integration]
    attributes: 
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team-test"
          password: "kur3nt0"

  - name: chef
    run_list:
      - recipe[kurento::chef]

  - name: kurento-dev-docker-32
    driver_config:
      privileged: true
      dockerfile: test/integration/x86/Dockerfile
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[kurento::kurento-dev-docker]
    attributes: 
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team-test"
          password: "kur3nt0"

  - name: kurento-dev-docker-64
    driver_config:
      privileged: true
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[kurento::kurento-dev-docker]
    attributes: 
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team-test"
          password: "kur3nt0"

  - name: kurento-dev-integration
    run_list:
      - recipe[kurento::kurento-dev-integration]
    attributes:
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team-test"
          password: "kur3nt0"

  - name: kurento-dev-media-server
    run_list:
      - recipe[kurento::kurento-dev-media-server]
    attributes:
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team-test"
          password: "kur3nt0"

  - name: kurento-dev-debian
    run_list:
      - recipe[kurento::kurento-dev-debian]
    attributes:
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team-test"
          password: "kur3nt0"

  - name: kurento-dev-tutorial
    run_list:
      - recipe[kurento::kurento-dev-tutorial]
    attributes:
      kurento:
        email: "jenkins@kurento.org"
        master-host: "ci.kurento.org"
        npm:
          email: "info@kurento.org"
          username: "kurento-maintainer-team-test"
          password: "kur3nt0"
